trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_REGISTRY: '<ACR_LOGIN_SERVER>'
  IMAGE_NAME: 'lokaltalent'
  AZURE_RESOURCE_GROUP: '<RESOURCE_GROUP>'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
- script: npm ci
- script: npm run build
- task: AzureCLI@2
  inputs:
    azureSubscription: '<SERVICE_CONNECTION>'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ACR_NAME=$(echo $(AZURE_CONTAINER_REGISTRY) | cut -d'.' -f1)
      az acr show --name $ACR_NAME --resource-group $(AZURE_RESOURCE_GROUP) || \
      az acr create --name $ACR_NAME --resource-group $(AZURE_RESOURCE_GROUP) --sku Basic
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: $(IMAGE_NAME)
    containerRegistry: $(AZURE_CONTAINER_REGISTRY)
    dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)
- task: AzureContainerApps@1
  inputs:
    azureSubscription: '<SERVICE_CONNECTION>'
    appName: '<CONTAINER_APP_NAME>'
    imageToDeploy: $(AZURE_CONTAINER_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
#  Additional step to bind a custom domain can be handled by Terraform or using
#  az containerapp hostname commands.
