trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'
- task: AzureCLI@2
  inputs:
    azureSubscription: '<SERVICE_CONNECTION>'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd $(System.DefaultWorkingDirectory)/deploy/terraform
      terraform init
      terraform apply -auto-approve
