name: Build and Push Medusa Image to ACR

on:
  workflow_dispatch: {}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: acrkanhaaappstore
      IMAGE_NAME: medusa
      KEY_VAULT_NAME: kv-kanhaa-app-store

    steps:
      - name: Checkout current repo (for workflows)
        uses: actions/checkout@v4

      - name: Set dependent environment variables
        run: |
          echo "REGISTRY_SERVER=${{ env.ACR_NAME }}.azurecr.io" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR credentials from Key Vault
        id: get_acr_creds
        run: |
          ACR_USERNAME=$(az keyvault secret show --vault-name ${{ env.KEY_VAULT_NAME }} --name "ACR-USERNAME" --query value -o tsv)
          ACR_PASSWORD=$(az keyvault secret show --vault-name ${{ env.KEY_VAULT_NAME }} --name "ACR-PASSWORD" --query value -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Clone Medusa starter repo
        run: |
          git clone https://github.com/medusajs/medusa-starter-default.git --depth=1 kanhaa-app-store

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build Docker image from Medusa starter
        run: |
          cd kanhaa-app-store
          docker build -t ${{ env.IMAGE_URI }} .
          docker tag ${{ env.IMAGE_URI }} ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.IMAGE_URI }}
          docker push ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:latest
