name: Deploy Medusa to Azure Container Apps

on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Medusa Deployment

    env:
      SUBSCRIPTION_ID: ${{ vars.AZ_SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ vars.RG_NAME }}
      ACR_NAME: ${{ vars.ACR_NAME }}
      ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT }}
      IMAGE_TAG: medusa:${{ github.sha }}
      REGISTRY_SERVER: ${{ vars.ACR_NAME }}.azurecr.io
      IMAGE_URI: ${{ vars.ACR_NAME }}.azurecr.io/medusa:${{ github.sha }}

      STORE_CORS: "http://localhost:3000"
      ADMIN_CORS: "http://localhost:7000"
      AUTH_CORS: "http://localhost:3000,http://localhost:7000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate and store JWT_SECRET and COOKIE_SECRET in Key Vault if missing
        shell: bash
        env:
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
          SUBSCRIPTION_ID: ${{ env.SUBSCRIPTION_ID }}
          KEY_VAULT_NAME: kv-kanhaa-app-store  # Adjust if KV name is different
        run: |
          # Check and create JWT_SECRET if missing
          if ! az keyvault secret show --v
